; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30136.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	__local_stdio_printf_options
PUBLIC	_vfprintf_s_l
PUBLIC	printf_s
PUBLIC	f
PUBLIC	main
EXTRN	__acrt_iob_func:PROC
EXTRN	__stdio_common_vfprintf_s:PROC
_DATA	SEGMENT
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
_DATA	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_vfprintf_s_l DD imagerel $LN3
	DD	imagerel $LN3+67
	DD	imagerel $unwind$_vfprintf_s_l
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$printf_s DD imagerel $LN3
	DD	imagerel $LN3+87
	DD	imagerel $unwind$printf_s
pdata	ENDS
pdata	SEGMENT
$pdata$f DD	imagerel $LN3
	DD	imagerel $LN3+21
	DD	imagerel $unwind$f
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+27
	DD	imagerel $unwind$main
pdata	ENDS
_DATA	SEGMENT
$SG9016	DB	'f', 00H
_DATA	ENDS
xdata	SEGMENT
$unwind$f DD	010401H
	DD	04204H
$unwind$main DD	010401H
	DD	06204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$printf_s DD 011801H
	DD	06218H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_vfprintf_s_l DD 011801H
	DD	06218H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
fptr$ = 32
main	PROC
; File C:\_main\_univer\Projects\TESTS\console building\array.c
; Line 11
$LN3:
	sub	rsp, 56					; 00000038H
; Line 12
	lea	rax, OFFSET FLAT:f
	mov	QWORD PTR fptr$[rsp], rax
; Line 13
	call	QWORD PTR fptr$[rsp]
; Line 14
	xor	eax, eax
; Line 15
	add	rsp, 56					; 00000038H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
f	PROC
; File C:\_main\_univer\Projects\TESTS\console building\array.c
; Line 6
$LN3:
	sub	rsp, 40					; 00000028H
; Line 7
	lea	rcx, OFFSET FLAT:$SG9016
	call	printf_s
; Line 8
	add	rsp, 40					; 00000028H
	ret	0
f	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT printf_s
_TEXT	SEGMENT
_Result$ = 32
_ArgList$ = 40
_Format$ = 64
printf_s PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 993
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+32], r9
	sub	rsp, 56					; 00000038H
; Line 996
	lea	rax, QWORD PTR _Format$[rsp+8]
	mov	QWORD PTR _ArgList$[rsp], rax
; Line 997
	mov	ecx, 1
	call	__acrt_iob_func
	mov	r9, QWORD PTR _ArgList$[rsp]
	xor	r8d, r8d
	mov	rdx, QWORD PTR _Format$[rsp]
	mov	rcx, rax
	call	_vfprintf_s_l
	mov	DWORD PTR _Result$[rsp], eax
; Line 998
	mov	QWORD PTR _ArgList$[rsp], 0
; Line 999
	mov	eax, DWORD PTR _Result$[rsp]
; Line 1000
	add	rsp, 56					; 00000038H
	ret	0
printf_s ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _vfprintf_s_l
_TEXT	SEGMENT
_Stream$ = 64
_Format$ = 72
_Locale$ = 80
_ArgList$ = 88
_vfprintf_s_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 673
$LN3:
	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 674
	call	__local_stdio_printf_options
	mov	rcx, QWORD PTR _ArgList$[rsp]
	mov	QWORD PTR [rsp+32], rcx
	mov	r9, QWORD PTR _Locale$[rsp]
	mov	r8, QWORD PTR _Format$[rsp]
	mov	rdx, QWORD PTR _Stream$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	__stdio_common_vfprintf_s
; Line 675
	add	rsp, 56					; 00000038H
	ret	0
_vfprintf_s_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __local_stdio_printf_options
_TEXT	SEGMENT
__local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
; Line 92
	lea	rax, OFFSET FLAT:?_OptionsStorage@?1??__local_stdio_printf_options@@9@9 ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 93
	ret	0
__local_stdio_printf_options ENDP
_TEXT	ENDS
END
